<html>
    <head>
        <link rel="shortcut icon" href="logo56.jpg" type="image/x-icon" />
        <title>Key Pairs for Digital Signature Schemes</title>
        <link href="content/app.css" rel="stylesheet"/>
        <script src="scripts/app.js" type="application/javascript"></script>
    </head>

    <body>
        <header class="container-fluid">
            <h1>Key Pairs for Digital Signature Schemes</h1>    
        </header>

        <fieldset>
            <p>Digital signatures are generated on data to provide origin authentication,
                assurance of data integrity or signatory non-repudiation. Digital signatures 
                are generated by a signer using a private key, and verified by a receiver using
                a public key.</p>

        </fieldset>

        <fieldset>   
            <button onclick="history.go(-1);">Back </button>                  
            <a href="KeyGeneration.php">
                <button>Key Generation</button>
            </a> 
            <a href="Home.php">
                    <button>Home</button>
            </a>
        </fieldset>


    </body>

</html>









