<html>
    <head>
        <link rel="shortcut icon" href="logo56.jpg" type="image/x-icon" />
        <title>Generation of Keys for Symmetric-Key Algorithms</title>
        <link href="content/app.css" rel="stylesheet"/>
        <script src="scripts/app.js" type="application/javascript"></script>
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
    </head>

    <body>
        <header class="container-fluid">
            <h1>Generation of Keys for Symmetric-Key Algorithms</h1>    
        </header>

        <fieldset>
            <legend>
                <p><h2>Secret Keys</h2></p>                   
            </legend>
            <p>
                Symmetric-key algorithms use the same (secret) key to both apply cryptographic protection to information
                and to remove or verify the protection. Keys used with symmetric-key algorithms must be known by only the
                entities authorized to apply, remove or verify the protection, and are commonly known as secret keys. 
                A secret key is often known by multiple entities that are said to share or own the secret key, although 
                it is not uncommon for a key to be generated, owned and used by a single entity (e.g., for secure storage).
            </p>
            
            <p>
                A secret key <b>shall</b> be generated by:
                <ul>
                    <li>One or more of the entities that will share the key, or</li>
                    <li>A Trusted Party that provides the key to the intended sharing entities in a secure manner. 
                        The Trusted Party must be trusted by all entities that will share the key not to disclose 
                        the key to unauthorized parties or otherwise misuse the key.</li>
                </ul>
            </p>

            <p>
                Instances where a symmetric key <i>K</i> could be used:
                <ul>
                    <li>Encrypt and decrypt data in an appropriate mode (e.g., using AES in the CTR mode)</li>
                    <li>Generate Message Authentication Codes (e.g., using AES in the CMAC mode)</li>
                    <li>Derive additional keys using a key derivation function where <i>K</i> is the pre-shared key that is 
                    used as the key-derivation key.</li>
                </ul>
            </p>
        </fieldset>

        <fieldset>
            <legend><h2>Methods of Generation of Symmetric Keys</h2></legend>

            <select onchange="location = this.options[this.selectedIndex].value;">  
                <option>Please select the method of symmetric key generation:</option>
                <option value=".php">Direct Generation of Symmetric Keys</option>
                <option value=".php">Symmetric Keys Generated Using Key-Agreement Schemes</option>
                <option value=".php">Symmetric Keys Derived From a Pre-shared Key</option> 
                <option value=".php">Symmetric Keys Derived From Passwords</option> 
                <option value=".php">Symmetric Keys Produced by Combining Multiple Keys and Other Data</option> 
            </select>

            <ul>                
                <li>Distributing the Generated Symmetric Key</li>
                <li>Replacement of Symmetric Keys</li>
                
            </ul>        

        </fieldset>

        <fieldset>        
            <button onclick="history.go(-1);">Back </button>    
            <a href="KeyGeneration.php">
                <button>Key Generation</button>
            </a>                
        
            <a href="Home.php">
                    <button>Home</button>
            </a>
        </fieldset>


    </body>

</html>









